language: haxe
haxe: "3.4.7"
dist: trusty
sudo: false

install:
  - haxelib install all --always
  - haxelib install hxcpp --always
  - haxelib dev hxparse libs/hxparse
  - haxelib dev hxtemplo libs/hxtemplo
  - haxelib dev hxargs libs/hxargs
  - haxelib dev markdown libs/haxe-markdown
  - haxelib dev dox libs/dox
  - haxelib list

script:
  - haxe gen.hxml
  - neko Gen.n
  # validate html
  - wget https://github.com/validator/validator/releases/download/18.8.29/vnu.jar_18.8.29.zip
  - unzip vnu.jar_18.8.29.zip
  - java -jar dist/vnu.jar --errors-only html/*.html # only for the top level html for now since there are many errors in e.g. js/html/*.html

deploy:
  provider: script
  script: haxe --run DeployGhPages
  on:
    branch: master
  skip_cleanup: true
